include:
  - ../../../Projects/mc/templates.yml
  - ../../../Projects/mc/mcMedia/project.yml
  - ../../../Projects/mc/mcTestability/project.yml
name: Shared
aggregateTargets:
  Shared:
    targets:
      - mcMedia_macOS
      - mcTestability_macOS
