include:
  - Vendor/mc/templates.yml
  - Vendor/mc/mcxMedia/project.yml
  - Vendor/mc/mcxTestabilityXC/project.yml
name: Shared
settings:
  AWL_LIB_SRC: Vendor/mc
  MACOSX_DEPLOYMENT_TARGET: 10.12
aggregateTargets:
  Shared:
    targets:
      - mcxMedia
      - mcxTestabilityXC
