

XCodeProjectFilePath = "#{ENV['PWD']}/CARingBuffer.xcodeproj"
XCodeProjectSchema = "Developer: Build Everything"

desc "Builds project."
lane :build do
   XcodeBuilder.new(XCodeProjectFilePath).build(XCodeProjectSchema)
end

desc "Cleans project."
lane :clean do
   XcodeBuilder.new(XCodeProjectFilePath).clean(XCodeProjectSchema)
end

desc "Builds when under CI (i.e. Travis)."
lane :ci do
   XcodeBuilder.new(XCodeProjectFilePath).ci("Developer: Analyze Performance")
   XcodeBuilder.new(XCodeProjectFilePath).ci("Demo: CAPlayThrough")
   XcodeBuilder.new(XCodeProjectFilePath).test("Logic Tests: Swift")
end

desc "Runs logic tests."
lane :test do
  XcodeBuilder.new(XCodeProjectFilePath).test("Logic Tests: Swift")
  XcodeBuilder.new(XCodeProjectFilePath).test("Logic Tests: C++")
end

desc "Deploy release to GitHub."
lane :deploy do
   releaseName = File.read("#{ENV['PWD']}/fastlane/ReleaseName.txt").strip
   releaseDescription = File.read("#{ENV['PWD']}/fastlane/ReleaseNotes.txt").strip
   github_release = set_github_release(
     repository_name: "vgorloff/CARingBuffer", api_token: ENV['AWL_GITHUB_TOKEN'], name: releaseName, tag_name: last_git_tag,
     description: releaseDescription, commitish: "master"
   )
end
