# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.95.0"

import '../Shared/Conf/Scripts/fastlane.rb'

desc "Runs all the tests (C++ and Swift)."
lane :test do
  XcodeTest("Logic Tests: Swift", "Logic Tests: C++")
end

desc "Builds project."
lane :build do
  XcodeBuild("CARBMeasure", "CAPlayThrough")
end

desc "Builds when under CI (i.e. Travis)."
lane :ci do
  XcodeBuildRelease("CARBMeasure", "CAPlayThrough")
  XcodeTest("Logic Tests: Swift")
end

desc "Cleans project."
lane :clean do
  XcodeClean("CAPlayThrough", "CARBMeasure", "Logic Tests: Swift", "Logic Tests: C++")
end
